"""Anonymous device identity.

The app has no login. Instead each install generates a UUID once, stores it in
the OS keychain (``expo-secure-store``), and sends it as ``X-Device-Id`` on
every request. Every row of user-owned data is scoped to that id.

This closes a real data-isolation hole: previously ``GET /api/favorites``
returned *every* favourite in the database and ``DELETE /api/favorites/{uid}``
deleted by station id with no owner check, so any client could read and delete
any other user's saved locations.

Important limitation, and the reason admin routes use real JWTs instead: a
device id is an *identifier*, not an *authenticator*. A client can send any
value it likes. It is sufficient to keep users' data separated from one
another; it must never be the only thing standing between a request and a
privileged operation.
"""

from __future__ import annotations

import re
from typing import Optional

from fastapi import Request

from app.core.errors import ValidationError
from app.core.security import DEVICE_ID_HEADER

# Accepts a bare or hyphenated UUID, plus opaque tokens of a similar shape, so
# clients aren't forced to a single UUID formatting convention.
_DEVICE_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]{15,63}$")


def normalise_device_id(raw: Optional[str]) -> Optional[str]:
    if not raw:
        return None
    candidate = raw.strip()
    if not _DEVICE_ID_RE.fullmatch(candidate):
        return None
    return candidate.lower()


async def require_device_id(request: Request) -> str:
    """FastAPI dependency for endpoints that read or write user-owned data."""
    device_id = normalise_device_id(request.headers.get(DEVICE_ID_HEADER))
    if not device_id:
        raise ValidationError(
            f"A valid {DEVICE_ID_HEADER} header is required. Send the stable "
            "per-install identifier generated by the client (16-64 characters, "
            "alphanumeric plus '-' and '_').",
        )
    return device_id


async def optional_device_id(request: Request) -> Optional[str]:
    """Dependency for public endpoints that personalise output when they can."""
    return normalise_device_id(request.headers.get(DEVICE_ID_HEADER))


__all__ = ["normalise_device_id", "optional_device_id", "require_device_id"]
